/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable no-mixed-spaces-and-tabs */
import {
	Nextdotjs,
	ReactJs,
	Html5,
	CssThree,
	Javascript,
	Angularjs,
	Typescript,
	Laravel,
	Nodedotjs,
	Tailwindcss,
	Firebase,
	Datagrip,
	Mysql,
	Postgresql,
	Git,
	Visualstudiocode,
	Vim,
	Gnubash,
	Chakraui,
	Bootstrap,
	Php,
	Python,
	Scikitlearn,
	Pandas,
	Numpy,
} from "@icons-pack/react-simple-icons";

export const Icons: IconType = {
	react: ReactJs,
	html: Html5,
	css: CssThree,
	javascript: Javascript,
	typescript: Typescript,
	laravel: Laravel,
	nodejs: Nodedotjs,
	tailwind: Tailwindcss,
	firebase: Firebase,
	datagrip: Datagrip,
	mysql: Mysql,
	postgres: Postgresql,
	git: Git,
	vscode: Visualstudiocode,
	vim: Vim,
	bash: Gnubash,
	nextjs: Nextdotjs,
	angular: Angularjs,
	chakraui: Chakraui,
	bootstrap: Bootstrap,
	php: Php,
	python: Python,
	scikit: Scikitlearn,
	pandas: Pandas,
	numpy: Numpy,
};

type IconType = {
	[key: string]: any;
};
